# Generated by Django 6.1 on 2026-09-02 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('marca', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='catalogo_pecas/')),
                ('quantidade_esperada', models.PositiveIntegerField(default=1)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='devolucoes.produto')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
