# Generated by Django 6.1 on 2026-09-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolucoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='catalogo_produtos/'),
        ),
    ]
