# Generated by Django 6.0.6 on 2026-09-07 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolucoes', '0002_grupofornecedor_produto_codigo_fabricante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo_fabricante',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código do fabricante'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='devolucoes.marca'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='SKU'),
        ),
    ]
