# Generated by Django 6.0.6 on 2026-09-08 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolucoes', '0006_peca_marca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compatibilidade',
            options={'ordering': ['produto__nome', 'peca__nome_generico']},
        ),
        migrations.AlterField(
            model_name='peca',
            name='nome_generico',
            field=models.CharField(max_length=200, verbose_name='Nome genérico'),
        ),
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_plataforma', models.CharField(max_length=100, verbose_name='Plataforma')),
                ('tipo_venda', models.CharField(choices=[('comum', 'Venda comum'), ('full', 'Venda FULL')], max_length=10, verbose_name='Tipo de venda')),
                ('numero_pedido', models.CharField(max_length=100, verbose_name='Número do pedido')),
                ('numero_nota_fiscal', models.CharField(max_length=100, verbose_name='Número da nota fiscal')),
                ('nome_cliente', models.CharField(max_length=200, verbose_name='Nome do cliente')),
                ('data_recebimento_cliente', models.DateField(verbose_name='Recebido pelo cliente em')),
                ('data_reclamacao_cliente', models.DateField(verbose_name='Reclamação/solicitação aberta em')),
                ('data_recebimento_por_nos', models.DateField(verbose_name='Recebido por nós em')),
                ('data_abertura_mediacao', models.DateField(blank=True, null=True, verbose_name='Mediação aberta em')),
                ('data_finalizacao_mediacao', models.DateField(blank=True, null=True, verbose_name='Mediação finalizada em')),
                ('reembolsado', models.BooleanField(blank=True, null=True, verbose_name='Reembolsado pela plataforma?')),
                ('anotacao_mediacao', models.TextField(blank=True, verbose_name='Anotações sobre a mediação')),
                ('motivo_reclamacao', models.TextField(verbose_name='Motivo da reclamação do cliente')),
                ('observacao_geral', models.TextField(blank=True, help_text='Algo que não é sobre nenhuma peça específica — ex: "veio outro produto no lugar".', verbose_name='Observação geral do produto')),
                ('destino_produto', models.CharField(choices=[('troca', 'Troca'), ('usado', 'Venda como usado')], max_length=10, verbose_name='Destino do produto')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='devolucoes.produto')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ConferenciaPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_esperada', models.PositiveIntegerField(verbose_name='Quantidade esperada')),
                ('quantidade_recebida', models.PositiveIntegerField(default=0, verbose_name='Quantidade recebida')),
                ('anotacao', models.TextField(blank=True, verbose_name='Anotação sobre esta peça')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conferencias', to='devolucoes.peca')),
                ('devolucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas_conferidas', to='devolucoes.devolucao')),
            ],
            options={
                'ordering': ['peca__nome_generico'],
                'unique_together': {('devolucao', 'peca')},
            },
        ),
        migrations.CreateModel(
            name='FotoConferenciaPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='conferencia_devolucao/pecas/')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='devolucoes.conferenciapeca')),
            ],
            options={
                'ordering': ['criada_em'],
            },
        ),
        migrations.CreateModel(
            name='FotoReclamacaoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='reclamacoes_cliente/')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('devolucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_reclamacao_cliente', to='devolucoes.devolucao')),
            ],
            options={
                'ordering': ['criada_em'],
            },
        ),
    ]
