# Generated by Django 6.0.6 on 2026-09-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolucoes', '0007_alter_compatibilidade_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucao',
            name='destino_produto',
            field=models.CharField(blank=True, choices=[('troca', 'Troca'), ('usado', 'Venda como usado')], max_length=10, verbose_name='Destino do produto'),
        ),
    ]
