# Generated by Django 6.0.6 on 2026-09-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolucoes', '0008_alter_devolucao_destino_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucao',
            name='nome_plataforma',
            field=models.CharField(choices=[('Shopee', 'Shopee'), ('Magalu', 'Magalu'), ('Tiktok Shop', 'Tiktok Shop'), ('Raia', 'Raia'), ('Mercado Livre', 'Mercado Livre'), ('Amazon', 'Amazon'), ('Mais correios', 'Mais correios')], max_length=100, verbose_name='Plataforma'),
        ),
    ]
