# Generated by Django 6.0.6 on 2026-09-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolucoes', '0009_alter_devolucao_nome_plataforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucao',
            name='data_venda',
            field=models.DateField(default='2026-09-08', verbose_name='Data da venda'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devolucao',
            name='nome_plataforma',
            field=models.CharField(choices=[('Amazon', 'Amazon'), ('Magalu', 'Magalu'), ('Mais correios', 'Mais correios'), ('Mercado Livre', 'Mercado Livre'), ('Raia', 'Raia'), ('Shopee', 'Shopee'), ('Tiktok Shop', 'Tiktok Shop')], max_length=100, verbose_name='Plataforma'),
        ),
    ]
