# Generated by Django 6.0.6 on 2026-09-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolucoes', '0010_devolucao_data_venda_alter_devolucao_nome_plataforma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucao',
            name='numero_pedido',
            field=models.CharField(max_length=100, unique=True, verbose_name='Número do pedido'),
        ),
    ]
