# Generated by Django 6.0.6 on 2026-09-18 04:10

import devolucoes.models.foto_conferencia_peca
import devolucoes.models.foto_reclamacao_cliente
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolucoes', '0011_alter_devolucao_numero_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoconferenciapeca',
            name='imagem',
            field=models.ImageField(upload_to=devolucoes.models.foto_conferencia_peca.caminho_foto_conferencia),
        ),
        migrations.AlterField(
            model_name='fotoreclamacaocliente',
            name='imagem',
            field=models.ImageField(upload_to=devolucoes.models.foto_reclamacao_cliente.caminho_foto_reclamacao_cliente),
        ),
    ]
