# Generated by Django 6.0.6 on 2026-09-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolucoes', '0012_alter_fotoconferenciapeca_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucao',
            name='relatorio_impresso_em',
            field=models.DateTimeField(blank=True, help_text='Preenchido manualmente pela usuária ao confirmar que já imprimiu de verdade — de propósito não marca sozinho ao abrir a tela de impressão, porque às vezes a impressão sai errada e precisa repetir (decisão de Matheus, 18/09/2026).', null=True, verbose_name='Relatório impresso em'),
        ),
    ]
