# Generated by Django 6.0.6 on 2026-09-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolucoes', '0013_devolucao_relatorio_impresso_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucao',
            name='preco_produto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço unitário pago pelo cliente (já com desconto) — vem da API do Mercado Livre pela tela Consultar Pedido, ou digitado manualmente.', max_digits=10, null=True, verbose_name='Preço do produto'),
        ),
        migrations.AddField(
            model_name='devolucao',
            name='valor_reembolsado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor que a plataforma efetivamente reembolsou ao cliente na mediação — sempre digitado manualmente, não tem de onde puxar pela API.', max_digits=10, null=True, verbose_name='Valor reembolsado'),
        ),
    ]
