# Generated by Django 6.0.6 on 2026-09-19 22:33

import devolucoes.models.foto_observacao_geral
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolucoes', '0014_devolucao_preco_produto_devolucao_valor_reembolsado'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoObservacaoGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=devolucoes.models.foto_observacao_geral.caminho_foto_observacao_geral)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('devolucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_observacao_geral', to='devolucoes.devolucao')),
            ],
            options={
                'ordering': ['criada_em'],
            },
        ),
    ]
