# Generated by Django 6.0.6 on 2026-09-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolucoes', '0015_fotoobservacaogeral'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloAnotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['texto'],
            },
        ),
    ]
