# Generated by Django 6.0.6 on 2026-09-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolucoes', '0016_modeloanotacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediacaoAvulsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=100, unique=True, verbose_name='Número do pedido')),
                ('nome_cliente', models.CharField(blank=True, max_length=200, verbose_name='Nome do cliente')),
                ('nome_produto', models.CharField(blank=True, help_text='Texto livre — essa mediação não está vinculada a um Produto cadastrado no catálogo.', max_length=200, verbose_name='Nome do produto')),
                ('data_abertura_mediacao', models.DateField(blank=True, null=True, verbose_name='Mediação aberta em')),
                ('data_finalizacao_mediacao', models.DateField(blank=True, null=True, verbose_name='Mediação finalizada em')),
                ('reembolsado', models.BooleanField(blank=True, null=True, verbose_name='Reembolsado pela plataforma?')),
                ('preco_produto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço do produto')),
                ('valor_reembolsado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor reembolsado')),
                ('motivo_reclamacao', models.TextField(blank=True, verbose_name='Motivo da reclamação do cliente')),
                ('observacao', models.TextField(blank=True, help_text='Por que essa mediação foi adicionada manualmente, contexto extra, etc.', verbose_name='Observação')),
                ('mediacao_visualizada_em', models.DateTimeField(blank=True, help_text='Preenchido automaticamente sempre que alguém abre a conversa dessa mediação na tela "Mediações ML" — é o que decide se tem mensagem nova não vista. Não é por usuário (o sistema ainda não tem login), é 1 timestamp só, compartilhado.', null=True, verbose_name='Mediação visualizada em')),
                ('mediacao_atualizada_em', models.DateTimeField(blank=True, help_text='Preenchido automaticamente sempre que o botão "Atualizar" (individual ou "Atualizar tudo") busca as mensagens dessa mediação na API do Mercado Livre. O sistema nunca atualiza sozinho — só nesse clique.', null=True, verbose_name='Mediação atualizada em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]