# Generated by Django 6.0.6 on 2026-09-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolucoes', '0017_mediacaoavulsa'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucao',
            name='mediacao_atualizada_em',
            field=models.DateTimeField(blank=True, help_text='Preenchido automaticamente sempre que o botão "Atualizar" (individual ou "Atualizar tudo") busca as mensagens dessa mediação na API do Mercado Livre. O sistema nunca atualiza sozinho — só nesse clique.', null=True, verbose_name='Mediação atualizada em'),
        ),
        migrations.AddField(
            model_name='devolucao',
            name='mediacao_visualizada_em',
            field=models.DateTimeField(blank=True, help_text='Preenchido automaticamente sempre que alguém abre a conversa dessa mediação na tela "Mediações ML" — é o que decide se tem mensagem nova não vista. Não é por usuário (o sistema ainda não tem login), é 1 timestamp só, compartilhado.', null=True, verbose_name='Mediação visualizada em'),
        ),
    ]