# Generated by Django 6.0.6 on 2026-09-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolucoes', '0018_devolucao_mediacao_atualizada_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucao',
            name='claim_id',
            field=models.CharField(blank=True, help_text='ID da claim no Mercado Livre — preenchido automaticamente quando a busca de mensagens roda pela 1ª vez (ainda não implementada). Usado pra montar os links "Ver reclamação"/"Ver mediação" no site do ML.', max_length=50, null=True, verbose_name='ID da reclamação/mediação no ML'),
        ),
        migrations.AddField(
            model_name='mediacaoavulsa',
            name='claim_id',
            field=models.CharField(blank=True, help_text='ID da claim no Mercado Livre — preenchido automaticamente quando a busca de mensagens roda pela 1ª vez (ainda não implementada). Usado pra montar os links "Ver reclamação"/"Ver mediação" no site do ML.', max_length=50, null=True, verbose_name='ID da reclamação/mediação no ML'),
        ),
    ]