# Generated by Django 6.0.6 on 2026-09-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolucoes', '0020_claim_mercado_livre_status_varredura_mediacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimmercadolivre',
            name='nome_cliente',
            field=models.CharField(blank=True, help_text='Buscado junto com a reclamação na varredura completa (GET /orders/{numero_pedido}) — existe pra mostrar/buscar em "Encontrados pelo Sistema", antes de virar MediacaoAvulsa/Devolucao.', max_length=200, verbose_name='Nome do cliente'),
        ),
        migrations.AddField(
            model_name='claimmercadolivre',
            name='nome_produto',
            field=models.CharField(blank=True, help_text='Mesmo texto livre do MediacaoAvulsa.nome_produto — buscado junto do nome do cliente.', max_length=200, verbose_name='Nome do produto'),
        ),
    ]
