# Generated by Django 6.0.6 on 2026-09-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolucoes', '0021_claimmercadolivre_nome_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucao',
            name='prazo_resposta',
            field=models.DateField(blank=True, help_text='Controle manual: o campo equivalente da API do Mercado Livre (due_date) existe mas nunca vem preenchido na prática (confirmado empiricamente, 20/09/2026) — preencha lendo o texto que o próprio ML manda no chat ("você tem até o dia X para responder").', null=True, verbose_name='Preciso responder até'),
        ),
        migrations.AddField(
            model_name='mediacaoavulsa',
            name='prazo_resposta',
            field=models.DateField(blank=True, help_text='Controle manual: o campo equivalente da API do Mercado Livre (due_date) existe mas nunca vem preenchido na prática (confirmado empiricamente, 20/09/2026) — preencha lendo o texto que o próprio ML manda no chat ("você tem até o dia X para responder").', null=True, verbose_name='Preciso responder até'),
        ),
    ]