# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devolucoes", "0022_devolucao_mediacaoavulsa_prazo_resposta"),
    ]

    operations = [
        migrations.AddField(
            model_name="claimmercadolivre",
            name="ultima_mensagem_de",
            field=models.CharField(
                blank=True,
                help_text='"ml" / "voce" / "cliente", ou None quando não dá pra saber com certeza (ex: meu_papel ainda não resolvido) -- mesmo critério de _formatar_mensagens. Denormalizado de mensagens.',
                max_length=10,
                null=True,
                verbose_name="Quem mandou a última mensagem",
            ),
        ),
        migrations.AddField(
            model_name="claimmercadolivre",
            name="ultima_mensagem_em",
            field=models.DateTimeField(
                blank=True,
                help_text='Denormalizado de mensagens -- ver comentário acima. Usado pra ordenar "Em acompanhamento" como um chat (mais recente primeiro) e pro indicador de mensagem não lida.',
                null=True,
                verbose_name="Data/hora da última mensagem",
            ),
        ),
        migrations.AddField(
            model_name="claimmercadolivre",
            name="ultima_mensagem_resumo",
            field=models.TextField(
                blank=True,
                help_text="Versão curta (sem HTML, truncada) do texto da última mensagem, pra pré-visualização de 1 linha na lista. Denormalizado de mensagens.",
                null=True,
                verbose_name="Resumo da última mensagem",
            ),
        ),
        migrations.AlterField(
            model_name="claimmercadolivre",
            name="meu_papel",
            field=models.CharField(
                blank=True,
                help_text='"respondent" ou "complainant" — vem de qual busca (players.role) encontrou o claim. Pode ficar None quando a resolução falha (API fora do ar na hora, ou o usuário não apareceu na lista de "players" do claim) — None aqui significa "não sabemos ainda", nunca deve ser tratado como equivalente a "complainant" (comprador). CORREÇÃO 21/09/2026: antes esse campo não aceitava null, e uma resolução que falhasse tentava gravar None mesmo assim — IntegrityError, derrubando a tela de detalhe daquele pedido.',
                max_length=20,
                null=True,
                verbose_name="Nosso papel nesta reclamação",
            ),
        ),
    ]
